// Package index regenerates index.md from the discovered entries. After D6 the file is generated
// output: its table format stays byte-compatible with the hand-maintained file so agents that read
// it keep working. Only the header paragraph changed, because the old "Keep this file current"
// prose told readers to do the one thing they must no longer do.
//
// The whole file is produced by Generate; Write puts it on disk atomically and Diff answers
// "has someone edited it by hand?" for kb doctor.
package index

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nickstrad/kb/internal/entry"
)

// Name is the generated file's name, relative to the repo root.
const Name = "index.md"

// lastReviewedPrefix marks the one line Diff ignores: it changes on every run without the entries
// changing, so comparing it would make every `kb doctor` report drift.
const lastReviewedPrefix = "Last reviewed:"

// header is everything above the first table. The paragraph is wrapped at the same ~95 columns as
// the rest of the repository's Markdown. %s is the "Last reviewed" date.
const header = "# Index\n" +
	"\n" +
	"Every knowledge entry under `data/`, with what it holds.\n" +
	"\n" +
	"**Optional snapshot generated by `kb index`; safe to delete and recreate.**\n" +
	"Use `kb search`, `kb list`, and `kb show` for current knowledge. Normal mutations and\n" +
	"`kb reindex` do not refresh this file; run `kb index` explicitly when an export is wanted.\n" +
	"Rows use each entry's `summary` front matter. See `AGENTS.md` for the rules and\n" +
	"`/update-knowledge-store` for the workflow. Directory companions are listed in their README.\n" +
	"\n" +
	lastReviewedPrefix + " %s\n" +
	"\n" +
	"## Knowledge entries\n" +
	"\n" +
	"| Entry | What it holds |\n" +
	"| --- | --- |\n"

// repositoryFiles is the static tail of index.md: the machinery that is not a knowledge entry.
// The Go module stays in kb/; its operator guide is a corpus entry at data/kb.md.
const repositoryFiles = "\n" +
	"## Repository files\n" +
	"\n" +
	"| Path | What it is |\n" +
	"| --- | --- |\n" +
	"| [AGENTS.md](AGENTS.md) | The contract: what belongs here, the generalization rule, entry shapes, naming, front matter, secrets policy. |\n" +
	"| `CLAUDE.md` | Symlink to `AGENTS.md`, so Claude Code and Codex read the same contract. |\n" +
	"| [index.md](index.md) | This file. |\n" +
	"| [kb/](kb/README.md) | Go source, tests, and installer for the kb CLI; operator guide in [data/kb.md](data/kb.md). |\n" +
	"| [skill/update-knowledge-store/](skill/update-knowledge-store/SKILL.md) | The `/update-knowledge-store` skill for Claude Code and Codex, plus the two entry templates. Symlinked into both agents' global skill directories. |\n"

// Today is the date Write and Diff callers normally pass as today: UTC, YYYY-MM-DD.
func Today() string {
	return time.Now().UTC().Format("2006-01-02")
}

// Generate renders the whole index.md for the given entries. today is written into the
// "Last reviewed:" line, formatted YYYY-MM-DD; it is a parameter so the caller owns the clock and
// tests are deterministic.
//
// Rows are sorted by their displayed link text ("droplet/", "grpc-reflection-and-grpcurl.md"),
// which is the order the hand-maintained file used. The summary is inserted verbatim apart from
// "|", which is escaped so it cannot split the cell.
func Generate(entries []entry.Entry, today string) ([]byte, error) {
	if today == "" {
		return nil, fmt.Errorf("index: today must be a YYYY-MM-DD date")
	}

	rows := make([]struct{ text, link, summary string }, 0, len(entries))
	for _, e := range entries {
		text, link, err := linkFor(e)
		if err != nil {
			return nil, err
		}
		rows = append(rows, struct{ text, link, summary string }{text, link, summaryOf(e)})
	}
	sort.SliceStable(rows, func(i, j int) bool { return rows[i].text < rows[j].text })

	var b strings.Builder
	fmt.Fprintf(&b, header, today)
	for _, r := range rows {
		fmt.Fprintf(&b, "| [%s](%s) | %s |\n", r.text, r.link, r.summary)
	}
	b.WriteString(repositoryFiles)
	return []byte(b.String()), nil
}

// Write regenerates index.md under root and replaces it atomically: the new content goes to a
// temp file in the same directory, is fsynced, and is then renamed over the old one, so a reader
// never sees a half-written map.
func Write(root string, entries []entry.Entry, today string) error {
	data, err := Generate(entries, today)
	if err != nil {
		return err
	}
	dest := filepath.Join(root, Name)
	tmp, err := os.CreateTemp(root, ".index.md.*")
	if err != nil {
		return fmt.Errorf("index: create temp file in %s: %w", root, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once the rename succeeded
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("index: write %s: %w", tmpName, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("index: sync %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("index: close %s: %w", tmpName, err)
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return fmt.Errorf("index: chmod %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, dest); err != nil {
		return fmt.Errorf("index: replace %s: %w", dest, err)
	}
	return nil
}

// Diff reports whether the index.md on disk differs from what Generate would produce now. The
// "Last reviewed:" line is ignored, since it moves with the clock and not with the entries; a
// missing index.md counts as differing, without an error. This is the kb doctor check.
func Diff(root string, entries []entry.Entry, today string) (bool, error) {
	want, err := Generate(entries, today)
	if err != nil {
		return false, err
	}
	got, err := os.ReadFile(filepath.Join(root, Name))
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, fmt.Errorf("index: read %s: %w", filepath.Join(root, Name), err)
	}
	return !bytes.Equal(stripLastReviewed(want), stripLastReviewed(got)), nil
}

// stripLastReviewed drops every "Last reviewed:" line so two renderings made on different days
// compare equal.
func stripLastReviewed(data []byte) []byte {
	lines := bytes.Split(data, []byte("\n"))
	kept := lines[:0]
	for _, line := range lines {
		if bytes.HasPrefix(bytes.TrimSpace(line), []byte(lastReviewedPrefix)) {
			continue
		}
		kept = append(kept, line)
	}
	return bytes.Join(kept, []byte("\n"))
}

// linkFor returns the displayed text and the link target for one entry: "foo.md" -> "foo.md",
// "foo.md"; a directory entry -> "droplet/", "droplet/README.md".
func linkFor(e entry.Entry) (text, link string, err error) {
	switch e.Kind {
	case entry.KindDir:
		dir := e.Dir
		if dir == "" { // tolerate an entry that carries only its path
			dir = strings.TrimSuffix(e.Path, "/README.md")
		}
		if dir == "" || dir == e.Path {
			return "", "", fmt.Errorf("index: directory entry %q has no directory name", e.Path)
		}
		return dir + "/", dir + "/README.md", nil
	case entry.KindFile:
		if e.Path == "" {
			return "", "", fmt.Errorf("index: file entry has an empty path")
		}
		return e.Path, e.Path, nil
	default:
		return "", "", fmt.Errorf("index: entry %q has unknown kind %q", e.Path, e.Kind)
	}
}

// summaryOf is the row's text: the entry's summary line, flattened to one line and with "|"
// escaped so it cannot break the table. An entry with no summary falls back to its title, and an
// entry with neither says so out loud rather than rendering an empty cell that looks intentional.
func summaryOf(e entry.Entry) string {
	s := cell(e.Meta.Summary)
	if s == "" {
		s = cell(e.Meta.Title)
	}
	if s == "" {
		return "(no `summary` in front matter — fix " + e.Path + ")"
	}
	return s
}

// cell flattens a value into a table cell: newlines become spaces, runs of whitespace collapse,
// and a literal "|" is escaped.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.Join(strings.Fields(s), " ")
	return strings.ReplaceAll(s, "|", `\|`)
}
